"""
Outreach recommendation engine - Part B (runs against the cleaned,
qualified dataset produced by crm_cleaning.run_cleaning()).

This module contains the DETERMINISTIC half of the outreach system:
eligibility (which stages never get a message), Last-Contacted timing
(premature vs. a genuine follow-up window), and the "500 other
retailers" specificity safety-net. These are testable rules, so they
live in code.

The CREATIVE half - the actual SUGGESTED_MESSAGE text, its
MESSAGE_LOGIC, and PERSONALISATION_ANGLE for every eligible lead - is
NOT generated by a function in this file. Per the brief's own
Architecture note, that content is authored directly in the Claude Code
session that runs this pipeline, for the current batch of qualified
leads, using the rules encoded here as the eligibility gate. There is
no algorithm here that could plausibly "write the message" - doing so
would mean either templating (which produces exactly the generic,
sounds-the-same-to-500-retailers copy the brief explicitly forbids) or
silently fabricating personalisation, which is against the rules this
whole system exists to enforce. See outreach_content.py (or the
generate-outreach CLI command's docstring) for where the authored
content is wired in.
"""
import re

import pandas as pd

# Stages that never get a drafted message - see the brief's Eligibility
# section. "Do Not Contact" is included defensively even though Rule 1
# of Part A already removes it entirely (NO_FIT_PATTERN matches "do not
# contact"), so it should never actually reach this function.
EXCLUDED_STAGES = {"In Conversation", "Not Interested", "Closed Lost", "Do Not Contact"}

# Contacted-within-N-days is "too premature to message again."
TOO_RECENT_DAYS = 7
# A deferred lead gets a suggested follow-up this many days after the
# last contact - i.e. roughly a week past the "too recent" cutoff.
FOLLOW_UP_DELAY_DAYS = 10
# Beyond this many days since last contact (with no reply), a Prospect/
# Contacted/Engaged/Opportunity-stage lead is treated as a
# re-engagement opportunity rather than a fresh cold approach.
LONG_GAP_DAYS = 28

# The "500 other retailers" test as a safety-net heuristic: these are
# the exact anti-pattern phrases the brief calls out by name (generic
# praise that would read identically sent to any business). This is
# NOT a general specificity detector - genuine specificity is a
# judgment call made when a line is drafted, not something a regex can
# fully verify - but it reliably catches the obvious failure mode.
GENERIC_COMPLIMENT_PATTERNS = [
    r"\bi love your (website|shop|store|business|page)\b",
    r"\byour (business|shop|store|website) looks (amazing|great|awesome|fantastic|incredible)\b",
    r"\b(great|nice|lovely|amazing|awesome) (shop|store|business|website)\b",
    r"\blove what you'?(re| are) doing\b",
    r"\bimpressive (store|shop|business)\b",
    r"\bhope you'?re well\b",
    r"\bjust checking in\b",
    r"\btouching base\b",
]
_GENERIC_RE = re.compile("|".join(GENERIC_COMPLIMENT_PATTERNS), re.I)


def passes_specificity_test(line: str) -> bool:
    """The "500 other retailers" test: if this line could be sent
    unchanged to 500 other businesses, it fails. Returns False for the
    known generic-compliment anti-patterns; True otherwise (a line
    passing this check is necessary but not sufficient for genuine
    personalisation - the actual specificity judgment happens when the
    line is drafted, not here)."""
    if not line or not str(line).strip():
        return False
    return not bool(_GENERIC_RE.search(str(line)))


def days_since_contact(last_contact_date, today):
    """last_contact_date is 'never' or a 'YYYY-MM-DD' string (Part A's
    output format). Returns None for 'never' / unparseable values."""
    if last_contact_date is None:
        return None
    s = str(last_contact_date).strip().lower()
    if s == "" or s == "never":
        return None
    try:
        d = pd.Timestamp(str(last_contact_date).strip())
    except (ValueError, TypeError):
        return None
    return (pd.Timestamp(today).normalize() - d.normalize()).days


def base_outreach_type_for_stage(stage_clean, pipeline_status):
    """The stage-driven default OUTREACH_TYPE before Last-Contacted
    timing is applied. Inbound leads are never treated as cold outreach
    (they've already engaged); Customer/Churned pipeline statuses get
    their own relationship-appropriate framing regardless of stage
    label. Engaged/Opportunity leads (Replied, Negotiating, Meeting
    Booked, Quote Sent, Visit Booked, Trialing, etc.) have already had
    genuine back-and-forth, so a follow-up to them is a re-engagement,
    never "assume zero awareness" cold outreach - only genuinely
    untouched Prospect/Contacted leads default to Cold (and are
    upgraded to Re-Engagement below if the silence since last contact
    has gone on long enough that a plain follow-up would feel odd)."""
    if stage_clean == "Inbound":
        return "Inbound"
    if pipeline_status == "Customer":
        return "Customer Check-In"
    if pipeline_status == "Churned":
        return "Churned-Win-Back"
    if pipeline_status in ("Engaged", "Opportunity"):
        return "Re-Engagement"
    return "Cold"


def assess_eligibility(row, today):
    """Returns a dict: eligible (bool), outreach_type (str),
    follow_up_date (str YYYY-MM-DD or None), reason (str - the
    deterministic half of MESSAGE_LOGIC for ineligible/deferred rows),
    days_since_contact (int or None).

    Eligibility is decided FIRST, before any drafting: excluded stages
    are never eligible, and a too-recent last contact defers rather
    than message. Everything else is eligible, with a stage/pipeline-
    derived OUTREACH_TYPE that the content-authoring step uses as its
    starting point (a lead contacted 8-28 days ago is still marked
    eligible here - the brief treats that window as a judgment call on
    whether genuine personalisation exists, which happens at drafting
    time, not as a hard rule this function can decide)."""
    stage_clean = row.get("stage_clean")
    pipeline_status = row.get("pipeline_status")
    last_contact = row.get("last_contact_date")
    dsc = days_since_contact(last_contact, today)

    if stage_clean in EXCLUDED_STAGES:
        return {
            "eligible": False,
            "outreach_type": "No Action",
            "follow_up_date": None,
            "reason": (
                f"Stage '{stage_clean}' is on the do-not-message list - "
                f"no message drafted, no assumptions made about prior conversation content."
            ),
            "days_since_contact": dsc,
        }

    if dsc is not None and dsc < TOO_RECENT_DAYS:
        follow_up = (pd.Timestamp(str(last_contact)).normalize()
                      + pd.Timedelta(days=FOLLOW_UP_DELAY_DAYS)).strftime("%Y-%m-%d")
        return {
            "eligible": False,
            "outreach_type": "Deferred",
            "follow_up_date": follow_up,
            "reason": (
                f"Last contacted {dsc} day{'s' if dsc != 1 else ''} ago - "
                f"another message this soon would be premature."
            ),
            "days_since_contact": dsc,
        }

    base_type = base_outreach_type_for_stage(stage_clean, pipeline_status)
    if base_type == "Cold" and dsc is not None and dsc > LONG_GAP_DAYS:
        base_type = "Re-Engagement"

    return {
        "eligible": True,
        "outreach_type": base_type,
        "follow_up_date": None,
        "reason": (
            f"Stage '{stage_clean}' (pipeline: {pipeline_status}), "
            f"last contacted {dsc if dsc is not None else 'never'} day(s) ago - eligible for outreach."
        ),
        "days_since_contact": dsc,
    }


def build_eligibility_frame(qualified_df: pd.DataFrame, today=None) -> pd.DataFrame:
    """Applies assess_eligibility() to every row of the cleaned,
    qualified dataset. Returns qualified_df with ELIGIBLE,
    OUTREACH_TYPE, RECOMMENDED_FOLLOW_UP_DATE, and
    _ELIGIBILITY_REASON columns added - the deterministic scaffold the
    content-authoring step fills SUGGESTED_MESSAGE/MESSAGE_LOGIC/
    PERSONALISATION_ANGLE on top of."""
    if today is None:
        today = pd.Timestamp.now().normalize()
    df = qualified_df.copy()
    assessed = df.apply(lambda row: assess_eligibility(row, today), axis=1, result_type="expand")
    df["ELIGIBLE"] = assessed["eligible"]
    df["OUTREACH_TYPE"] = assessed["outreach_type"]
    df["RECOMMENDED_FOLLOW_UP_DATE"] = assessed["follow_up_date"]
    df["_ELIGIBILITY_REASON"] = assessed["reason"]
    df["_DAYS_SINCE_CONTACT"] = assessed["days_since_contact"]
    return df
